title:           Instanciando
description:     Instanciando
disqus_shortname:
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: 

# SEO
lang: pt_BR
social:
  name: Eduardo Domene Junior
  links:
    - https://twitter.com/_Edudjr_
    - https://github.com/edudjr
    - https://www.linkedin.com/in/edudjr/
  twitter_image: https://s19.postimg.org/m2y2vw3xv/Zyp_AYkw_G.png

# Owner/author information
owner:
  name:           Eduardo Domene Junior
  avatar:         avatar.jpg
  bio:
  email:          eduardo.djr@hotmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: https://twitter.com/_Edudjr_
  facebook:
  github: https://github.com/edudjr
  stackexchange:
  linkedin: https://www.linkedin.com/in/edudjr/
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-97047623-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Sao_Paulo
future:      false  # publish future dated posts --  true, false (default)
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
